### ISSUE TITLE
scripts/eq36cfg

### ISSUE THREAD

**Issue by Tucker-Ely** [39alpha/eq3_6#1]
Do we still need this shell script to set up the local environment?

If not, and if there are other original setup files that are no longer needed, maybe we place them in a historical directory and leave them with our release, with an appropriate readme?

Also, the items in this file can be handled in the python code that we use for all execution. Not sure if this is a better way to go or not.

Right now, EQ36 does not run in the architecture you have set up because these environmental variables are not established. Also, if we keep this file, we need to amend its contents to reflect the new folder architecture.

**Comment by dglmoore** [comment]
As of a3e1ca7df7654c462c3513edcddd7d39842ac25e we no longer need the scripts, and all but `scripts/xcif36` have been removed. We are keeping that one around because `xcon3` and `xcon6` have not been updated to take command line arguments.
