### ISSUE TITLE
db

### ISSUE THREAD

**Issue by Tucker-Ely** [39alpha/eq3_6#2]
The db folder has traditionally been alongside the bin. I notice that you now have it in the test folder. This can obviously be changed with paths, but i'm pretty sure all of the default settings (such as those established when sourcing the eq36cfg file), have db alongside bin.

The db folder contains the data0 files, which house the thermodynamic data that are used to solve any given problem (as laid out in 3i.6i files). Eventually we will want this to be dynamically populated for different problems, and not static as was originally designed. This is structural problem I have yet to address. At this time, I manually populate the db folder depending on what class of problem I am solving, with data0 files built by other codes I have written.

**Comment by dglmoore** [comment]
With a3e1ca7df7654c462c3513edcddd7d39842ac25e we can now provide paths as command line arguments to the executables `eq3nr`, `eq6` and `eqpt`. For example,
```bash
$ eq3nr data0.ymp
```
This means we no longer need `db` files to be in any particular location.
